# Generated by Django 5.2.4 on 2025-08-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=50)),
                ('icon', models.ImageField(upload_to='award-icon/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Awards',
                'db_table': 'award',
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='nominee-images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('telegram', models.CharField(max_length=25)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='main.award')),
            ],
            options={
                'verbose_name_plural': 'Nominees',
                'db_table': 'nominee',
            },
        ),
    ]
