# Generated by Django 5.2.4 on 2025-11-08 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='nominee-images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('telegram', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Nominees',
                'db_table': 'nominee',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=50)),
                ('icon', models.ImageField(upload_to='award-icons/')),
                ('slug', models.SlugField(unique=True)),
                ('awardImage', models.ImageField(blank=True, null=True, upload_to='award-images/')),
                ('is_major', models.BooleanField(default=False)),
                ('nominees', models.ManyToManyField(related_name='awards', to='main.nominee')),
            ],
            options={
                'verbose_name_plural': 'Awards',
                'db_table': 'award',
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='winners-images/')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='main.award')),
            ],
            options={
                'verbose_name_plural': 'Winners',
                'db_table': 'winner',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.award')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.nominee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Votes',
                'db_table': 'vote',
                'unique_together': {('user', 'award')},
            },
        ),
    ]
