# Generated by Django 5.2.4 on 2025-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='awardImage',
            field=models.ImageField(blank=True, null=True, upload_to='award-images/'),
        ),
        migrations.AlterField(
            model_name='award',
            name='icon',
            field=models.ImageField(upload_to='award-icons/'),
        ),
    ]
