# Generated by Django 5.2.4 on 2025-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_award_awardimage_alter_award_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='award',
        ),
        migrations.AddField(
            model_name='nominee',
            name='award',
            field=models.ManyToManyField(related_name='nominees', to='main.award'),
        ),
    ]
