# Generated by Django 5.2.4 on 2025-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_nominee_award_nominee_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='award',
        ),
        migrations.AddField(
            model_name='award',
            name='nominees',
            field=models.ManyToManyField(related_name='awards', to='main.nominee'),
        ),
    ]
