# Generated by Django 5.2.4 on 2025-08-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_nominee_award_award_nominees'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
    ]
