# Generated by Django 5.2.4 on 2025-08-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='winners-images/')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='main.award')),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='main.nominee')),
            ],
            options={
                'verbose_name_plural': 'Winners',
                'db_table': 'winner',
            },
        ),
    ]
