# Generated by Django 5.2.4 on 2025-08-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='nominee',
            field=models.CharField(max_length=30),
        ),
    ]
